on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    # activate conda environment automatically
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - uses: actions/checkout@v6

      - name: Install Runner Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v2
        with:
          create-args: python=${{ matrix.python-version }}
          environment-name: legacy-env
          cache-environment: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build Wheel (legacy python)
        run: uv build
        if: matrix.python-version == '3.6' || matrix.python-version == '3.7'

      - name: Install dependencies
        run: |
          TARGET_PY="$HOME/micromamba/envs/legacy-env/bin/python"
          uv build
          uv export --no-emit-project -o requirements.txt
          uv export --group dev --no-emit-project -o requirements.dev.txt

          if [[ "${{ matrix.python-version }}" == "3.6" ]] || [[ "${{ matrix.python-version }}" == "3.7" ]]; then
            echo "Legacy python detected, using standard pip"

            "$TARGET_PY" -m pip install -r requirements.txt
            "$TARGET_PY" -m pip install -r requirements.dev.txt
            "$TARGET_PY" -m pip install dist/*.whl
          else
            # we use `uv pip` instead of `uv sync` because we are installing into the conda environment, not the uv one.
            # also we have this second check because uv should be a bit faster than bare pip for modern tests
            uv pip install --python "$TARGET_PY" -r requirements.txt
            uv pip install --python "$TARGET_PY" -r requirements.dev.txt
            uv pip install --python "$TARGET_PY" -e .
          fi

      - name: Static type checking
        # do NOT try running mypy on 3.6
        if: matrix.python-version != '3.6'
        run: mypy .

      - name: Run unit tests
        run: pytest . --cov=randfacts --cov-report=term-missing --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: python-${{ matrix.python-version }}
